-- Transfer system: relationships, transfer requests, archived plans, nullable patient doctor

CREATE TABLE IF NOT EXISTS public."DoctorPatientRelationships" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "AssignedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EndedAt" timestamp,
    "DiagnosisTextSnapshot" text,
    "DiagnosisFileUrlSnapshot" text,
    CONSTRAINT "PK_DoctorPatientRelationships" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorPatientRelationships_Doctors"
        FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DoctorPatientRelationships_Patients"
        FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_DoctorPatientRelationships_DoctorId"
    ON public."DoctorPatientRelationships" ("DoctorId");
CREATE INDEX IF NOT EXISTS "IX_DoctorPatientRelationships_PatientId"
    ON public."DoctorPatientRelationships" ("PatientId");

CREATE TABLE IF NOT EXISTS public."TransferRequests" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "FromDoctorId" integer,
    "ToDoctorId" integer NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Pending',
    "Message" text,
    "InitiatedByDoctorId" integer,
    "CreatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "RespondedAt" timestamp,
    CONSTRAINT "PK_TransferRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransferRequests_Patients"
        FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TransferRequests_FromDoctors"
        FOREIGN KEY ("FromDoctorId") REFERENCES public."Doctors"("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_TransferRequests_ToDoctors"
        FOREIGN KEY ("ToDoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TransferRequests_PatientId"
    ON public."TransferRequests" ("PatientId");
CREATE INDEX IF NOT EXISTS "IX_TransferRequests_ToDoctorId_Status"
    ON public."TransferRequests" ("ToDoctorId", "Status");

ALTER TABLE public."TherapyPlans"
    ADD COLUMN IF NOT EXISTS "IsArchived" boolean NOT NULL DEFAULT false;

-- Make Patient.DoctorId nullable
ALTER TABLE public."Patients" ALTER COLUMN "DoctorId" DROP NOT NULL;

-- Backfill relationships for existing patients
INSERT INTO public."DoctorPatientRelationships" ("DoctorId", "PatientId", "AssignedAt", "EndedAt")
SELECT p."DoctorId", p."Id", p."CreatedAt", NULL
FROM public."Patients" p
WHERE p."DoctorId" IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM public."DoctorPatientRelationships" r
      WHERE r."DoctorId" = p."DoctorId" AND r."PatientId" = p."Id" AND r."EndedAt" IS NULL
  );

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260617000000_TransferSystem', '8.0.0')
ON CONFLICT DO NOTHING;
