-- ============================================================
-- Schema Migration - Adding Admin, DoctorReview, and other enhancements
-- ============================================================

-- ============================================================
-- 1. ADMINS TABLE (new)
-- ============================================================
CREATE TABLE IF NOT EXISTS public."Admins" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_Admins_Email" UNIQUE ("Email")
);

ALTER TABLE public."Admins" OWNER TO postgres;


-- ============================================================
-- 2. DOCTORREVIEW TABLE (new) - for patient reviews of doctors
-- ============================================================
CREATE TABLE IF NOT EXISTS public."DoctorReviews" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "Rating" integer NOT NULL CHECK ("Rating" >= 1 AND "Rating" <= 5),
    "Comment" text,
    "CreatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_DoctorReviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DoctorReviews_Doctors"
        FOREIGN KEY ("DoctorId")
        REFERENCES public."Doctors"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DoctorReviews_Patients"
        FOREIGN KEY ("PatientId")
        REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_DoctorReviews_DoctorPatient"
        UNIQUE ("DoctorId", "PatientId")
);

ALTER TABLE public."DoctorReviews" OWNER TO postgres;

CREATE INDEX IF NOT EXISTS "IX_DoctorReviews_DoctorId"
    ON public."DoctorReviews" USING btree ("DoctorId");
CREATE INDEX IF NOT EXISTS "IX_DoctorReviews_PatientId"
    ON public."DoctorReviews" USING btree ("PatientId");


-- ============================================================
-- 3. DOCTORS: add new columns, keep existing ones
-- ============================================================
DO $$ 
BEGIN
    -- Add CvText if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='CvText') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "CvText" text;
    END IF;
    
    -- Add CvFileUrl if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='CvFileUrl') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "CvFileUrl" character varying(500);
    END IF;
    
    -- Add DateOfBirth if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='DateOfBirth') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "DateOfBirth" date;
    END IF;
    
    -- Add PhoneNumber if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='PhoneNumber') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "PhoneNumber" character varying(30);
    END IF;
    
    -- Add Address if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='Address') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "Address" text;
    END IF;
    
    -- Add CommunicationInfo if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='CommunicationInfo') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "CommunicationInfo" text;
    END IF;
    
    -- Add IsBlocked if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='IsBlocked') THEN
        ALTER TABLE public."Doctors" ADD COLUMN "IsBlocked" boolean NOT NULL DEFAULT false;
    END IF;
END $$;

-- Migrate existing CV data into CvFileUrl if CV column exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Doctors' AND column_name='CV') THEN
        UPDATE public."Doctors" SET "CvFileUrl" = "CV" WHERE "CV" IS NOT NULL;
        ALTER TABLE public."Doctors" DROP COLUMN "CV";
    END IF;
END $$;


-- ============================================================
-- 4. PATIENTS: replace Age with DateOfBirth, add PhoneNumber,
--              split Diagnosis into text + file
-- ============================================================
DO $$
BEGIN
    -- Add DateOfBirth if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='DateOfBirth') THEN
        ALTER TABLE public."Patients" ADD COLUMN "DateOfBirth" date;
    END IF;
    
    -- Add PhoneNumber if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='PhoneNumber') THEN
        ALTER TABLE public."Patients" ADD COLUMN "PhoneNumber" character varying(30);
    END IF;
    
    -- Add DiagnosisText if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='DiagnosisText') THEN
        ALTER TABLE public."Patients" ADD COLUMN "DiagnosisText" text;
    END IF;
    
    -- Add DiagnosisFileUrl if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='DiagnosisFileUrl') THEN
        ALTER TABLE public."Patients" ADD COLUMN "DiagnosisFileUrl" text;
    END IF;
    
    -- Add IsBlocked if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='IsBlocked') THEN
        ALTER TABLE public."Patients" ADD COLUMN "IsBlocked" boolean NOT NULL DEFAULT false;
    END IF;
END $$;

-- Migrate existing Diagnosis text → DiagnosisText if Diagnosis exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='Diagnosis') THEN
        UPDATE public."Patients" SET "DiagnosisText" = "Diagnosis" WHERE "Diagnosis" IS NOT NULL;
        -- Drop old columns only if they exist
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='Diagnosis') THEN
            ALTER TABLE public."Patients" DROP COLUMN "Diagnosis";
        END IF;
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Patients' AND column_name='Age') THEN
            ALTER TABLE public."Patients" DROP COLUMN "Age";
        END IF;
    END IF;
END $$;


-- ============================================================
-- 5. EXERCISES: remove redundant Difficulty varchar column if exists
-- ============================================================
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='Exercises' AND column_name='Difficulty' AND data_type='character varying') THEN
        ALTER TABLE public."Exercises" DROP COLUMN "Difficulty";
    END IF;
END $$;


-- ============================================================
-- 6. VOCABULARYEXERCISES junction table (new)
-- ============================================================
CREATE TABLE IF NOT EXISTS public."VocabularyExercises" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VocabularyId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "DifficultyLevelId" integer NOT NULL,
    CONSTRAINT "PK_VocabularyExercises" PRIMARY KEY ("Id"),
    CONSTRAINT "UQ_VocabExercise_Combo"
        UNIQUE ("VocabularyId", "ExerciseId", "DifficultyLevelId"),
    CONSTRAINT "FK_VocabExercises_Vocabularies"
        FOREIGN KEY ("VocabularyId")
        REFERENCES public."Vocabularies"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VocabExercises_Exercises"
        FOREIGN KEY ("ExerciseId")
        REFERENCES public."Exercises"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VocabExercises_DifficultyLevels"
        FOREIGN KEY ("DifficultyLevelId")
        REFERENCES public."DifficultyLevels"("Id") ON DELETE CASCADE
);

ALTER TABLE public."VocabularyExercises" OWNER TO postgres;

CREATE INDEX IF NOT EXISTS "IX_VocabularyExercises_VocabularyId"
    ON public."VocabularyExercises" USING btree ("VocabularyId");
CREATE INDEX IF NOT EXISTS "IX_VocabularyExercises_ExerciseId"
    ON public."VocabularyExercises" USING btree ("ExerciseId");
CREATE INDEX IF NOT EXISTS "IX_VocabularyExercises_DifficultyLevelId"
    ON public."VocabularyExercises" USING btree ("DifficultyLevelId");


-- ============================================================
-- 7. INVITATIONCODES: allow admin-generated codes too
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='InvitationCodes' AND column_name='AdminId') THEN
        ALTER TABLE public."InvitationCodes"
            ADD COLUMN "AdminId" integer,
            ADD CONSTRAINT "FK_InvitationCodes_Admins_AdminId"
                FOREIGN KEY ("AdminId")
                REFERENCES public."Admins"("Id") ON DELETE SET NULL;
        
        CREATE INDEX "IX_InvitationCodes_AdminId"
            ON public."InvitationCodes" USING btree ("AdminId");
    END IF;
END $$;


-- ============================================================
-- 8. WEEKLYREPORTS: add ON DELETE SET NULL for TherapyPlanId
-- ============================================================
DO $$
DECLARE
    constraint_exists boolean;
BEGIN
    -- Check if the old constraint exists
    SELECT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'WeeklyReports' 
        AND constraint_name = 'FK_WeeklyReports_TherapyPlans_TherapyPlanId'
    ) INTO constraint_exists;
    
    IF constraint_exists THEN
        ALTER TABLE public."WeeklyReports"
            DROP CONSTRAINT "FK_WeeklyReports_TherapyPlans_TherapyPlanId";
        
        ALTER TABLE public."WeeklyReports"
            ADD CONSTRAINT "FK_WeeklyReports_TherapyPlans_TherapyPlanId"
                FOREIGN KEY ("TherapyPlanId")
                REFERENCES public."TherapyPlans"("Id") ON DELETE SET NULL;
    END IF;
END $$;


-- ============================================================
-- 9. EF Migrations history entry
-- ============================================================
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602000000_SchemaV2', '8.0.0')
ON CONFLICT DO NOTHING;
