-- Patient Analytics & Progress Tracking schema
-- Normalized category performance + pronunciation patterns (AI-ready)

CREATE TABLE IF NOT EXISTS public."TrainingSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientId" integer NOT NULL,
    "ExerciseProgressId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "PlanExerciseId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "TotalDurationSeconds" integer NOT NULL DEFAULT 0,
    "WordsCompleted" integer NOT NULL DEFAULT 0,
    "FirstAttemptCorrectCount" integer NOT NULL DEFAULT 0,
    "AverageSimilarityScore" double precision NOT NULL DEFAULT 0,
    "AccuracyPercent" double precision NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_TrainingSessions_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TrainingSessions_ExerciseProgresses" FOREIGN KEY ("ExerciseProgressId") REFERENCES public."ExerciseProgresses"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TrainingSessions_Exercises" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_TrainingSessions_PlanExercises" FOREIGN KEY ("PlanExerciseId") REFERENCES public."PlanExercises"("Id") ON DELETE RESTRICT,
    CONSTRAINT "UQ_TrainingSessions_ExerciseProgressId" UNIQUE ("ExerciseProgressId")
);

CREATE TABLE IF NOT EXISTS public."SpeechAttempts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientId" integer NOT NULL,
    "TrainingSessionId" integer NOT NULL,
    "ExerciseProgressId" integer NOT NULL,
    "ExerciseId" integer NOT NULL,
    "VocabularyId" integer,
    "ExpectedWord" character varying(200) NOT NULL,
    "RecognizedWord" character varying(200) NOT NULL DEFAULT '',
    "SimilarityScore" double precision NOT NULL DEFAULT 0,
    "AttemptNumber" integer NOT NULL DEFAULT 1,
    "IsCorrect" boolean NOT NULL DEFAULT false,
    "AudioDurationSeconds" double precision NOT NULL DEFAULT 0,
    "Category" character varying(100),
    "AttemptedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "FK_SpeechAttempts_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpeechAttempts_TrainingSessions" FOREIGN KEY ("TrainingSessionId") REFERENCES public."TrainingSessions"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpeechAttempts_ExerciseProgresses" FOREIGN KEY ("ExerciseProgressId") REFERENCES public."ExerciseProgresses"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SpeechAttempts_Exercises" FOREIGN KEY ("ExerciseId") REFERENCES public."Exercises"("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SpeechAttempts_Vocabularies" FOREIGN KEY ("VocabularyId") REFERENCES public."Vocabularies"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public."ProgressSnapshots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientId" integer NOT NULL,
    "TrainingSessionId" integer NOT NULL,
    "SnapshotDate" timestamp with time zone NOT NULL,
    "CumulativeTrainingTimeSeconds" integer NOT NULL DEFAULT 0,
    "AccuracyPercent" double precision NOT NULL DEFAULT 0,
    "FirstAttemptSuccessRate" double precision NOT NULL DEFAULT 0,
    "AverageSimilarity" double precision NOT NULL DEFAULT 0,
    "AverageAttemptsPerWord" double precision NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_ProgressSnapshots_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProgressSnapshots_TrainingSessions" FOREIGN KEY ("TrainingSessionId") REFERENCES public."TrainingSessions"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_ProgressSnapshots_TrainingSessionId" UNIQUE ("TrainingSessionId")
);

CREATE TABLE IF NOT EXISTS public."CategoryPerformanceSnapshots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProgressSnapshotId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "Category" character varying(100) NOT NULL,
    "AccuracyPercent" double precision NOT NULL DEFAULT 0,
    "AverageSimilarity" double precision NOT NULL DEFAULT 0,
    "AverageAttemptsPerWord" double precision NOT NULL DEFAULT 0,
    "WordsAttempted" integer NOT NULL DEFAULT 0,
    "TrendDirection" character varying(30) NOT NULL DEFAULT 'InsufficientData',
    "PreviousAccuracyPercent" double precision,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_CategoryPerformanceSnapshots_ProgressSnapshots" FOREIGN KEY ("ProgressSnapshotId") REFERENCES public."ProgressSnapshots"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CategoryPerformanceSnapshots_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."SessionClinicalReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientId" integer NOT NULL,
    "TrainingSessionId" integer NOT NULL,
    "SessionDurationSeconds" integer NOT NULL DEFAULT 0,
    "ExercisesCompleted" integer NOT NULL DEFAULT 0,
    "AccuracyRate" double precision NOT NULL DEFAULT 0,
    "FirstAttemptSuccessRate" double precision NOT NULL DEFAULT 0,
    "AveragePronunciationSimilarity" double precision NOT NULL DEFAULT 0,
    "StrengthAreasJson" text,
    "WeaknessAreasJson" text,
    "RecommendedFocusJson" text,
    "AnalysisSource" character varying(30) NOT NULL DEFAULT 'Deterministic',
    "GeneratedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_SessionClinicalReports_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SessionClinicalReports_TrainingSessions" FOREIGN KEY ("TrainingSessionId") REFERENCES public."TrainingSessions"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_SessionClinicalReports_TrainingSessionId" UNIQUE ("TrainingSessionId")
);

CREATE TABLE IF NOT EXISTS public."PronunciationPatterns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PatientId" integer NOT NULL,
    "VocabularyId" integer,
    "ExpectedPattern" character varying(200) NOT NULL,
    "RecognizedPattern" character varying(200) NOT NULL,
    "PatternType" character varying(50) NOT NULL DEFAULT 'Substitution',
    "Category" character varying(100),
    "OccurrenceCount" integer NOT NULL DEFAULT 1,
    "AverageSimilarityScore" double precision NOT NULL DEFAULT 0,
    "SeverityScore" double precision NOT NULL DEFAULT 0,
    "AnalysisSource" character varying(30) NOT NULL DEFAULT 'Deterministic',
    "MetadataJson" text,
    "IsActive" boolean NOT NULL DEFAULT true,
    "FirstDetectedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "LastDetectedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_PronunciationPatterns_Patients" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PronunciationPatterns_Vocabularies" FOREIGN KEY ("VocabularyId") REFERENCES public."Vocabularies"("Id") ON DELETE SET NULL,
    CONSTRAINT "UQ_PronunciationPatterns_Patient_Patterns" UNIQUE ("PatientId", "ExpectedPattern", "RecognizedPattern", "PatternType")
);

CREATE INDEX IF NOT EXISTS "IX_SpeechAttempts_PatientId_AttemptedAt" ON public."SpeechAttempts" ("PatientId", "AttemptedAt");
CREATE INDEX IF NOT EXISTS "IX_SpeechAttempts_TrainingSessionId" ON public."SpeechAttempts" ("TrainingSessionId");
CREATE INDEX IF NOT EXISTS "IX_TrainingSessions_PatientId_StartTime" ON public."TrainingSessions" ("PatientId", "StartTime");
CREATE INDEX IF NOT EXISTS "IX_ProgressSnapshots_PatientId_SnapshotDate" ON public."ProgressSnapshots" ("PatientId", "SnapshotDate");
CREATE INDEX IF NOT EXISTS "IX_CategoryPerformanceSnapshots_PatientId_Category" ON public."CategoryPerformanceSnapshots" ("PatientId", "Category");
CREATE INDEX IF NOT EXISTS "IX_CategoryPerformanceSnapshots_ProgressSnapshotId" ON public."CategoryPerformanceSnapshots" ("ProgressSnapshotId");
CREATE INDEX IF NOT EXISTS "IX_PronunciationPatterns_PatientId_IsActive" ON public."PronunciationPatterns" ("PatientId", "IsActive");
CREATE INDEX IF NOT EXISTS "IX_SessionClinicalReports_PatientId_GeneratedAt" ON public."SessionClinicalReports" ("PatientId", "GeneratedAt");
